name: Package VSCode Extension
on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node-js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install vsce
        run: npm install vsce

      - name: Package Extionsion
        working-directory: vscode_extension
        run: vsce package
      - uses: actions/upload-artifact@v3
        with:
          name: whoisworking.vsix
          path: vscode_extension/whoisworking*.vsix
          